Make applet optional in scheduler
google/wasefire pull request #562
Opened 2024-08-02 15:29 UTC by ia0

This is a first step towards dynamic loading and unloading of applets. For now, at most one applet may be loaded at a time.

2024-08-02 15:46 UTC, ia0-review approved these changes

2024-08-02 15:58 UTC, ia0-review requested changes
We should fix `cargo xtask --native applet rust link_test --features=native runner nordic --features=software-crypto` first.

2024-08-05 07:13 UTC, ia0 commented
Native builds have been fixed by #564. Running `hwci.sh nordic` again.

2024-08-05 07:13 UTC, ia0-review approved these changes

2024-08-05 07:24 UTC, ia0 commented
Hardware tests passed on Nordic.

2024-08-05 07:25 UTC, merged