Support applet install and uninstall
google/wasefire pull request #617
Opened 2024-09-26 09:56 UTC by ia0

Fixes #577

2024-09-26 10:18 UTC, ia0-review requested changes
Only reviewed up to and including `crates/cli`. Will do another iteration after fixes.

2024-09-26 10:18 UTC, ia0-review commented on crates/cli-tools/CHANGELOG.md
> +- Change the default connection timeout from 1 seconds to infinite (0 seconds)
typo

2024-09-26 10:18 UTC, ia0-review commented on crates/cli-tools/CHANGELOG.md
> +- Add `action::Wait::set_period()` and `impl Default for action::Wait`
already contained below

2024-09-26 11:36 UTC, ia0-review approved these changes

2024-09-26 11:53 UTC, ia0 commented
There are 2 issues:
- Footprint logic must be updated to take into account that wasm applets are not embedded anymore.
- Seems like using unix socket on Github doesn't work (maybe use something else than `/tmp/wasefire`).

2024-09-26 13:32 UTC, ia0 commented
There's a few issues that might be worse fixing after this PR:
- `protocol-usb` is used with both `device` and `host`. The feature documentation in `Cargo.toml` should be fixed and a test with both features should be added to `test.sh`.
- `ensure_applet` assumes `thumbv7em-none-eabi` which is not always true. We use `i686-unknown-linux-gnu` in `scheduler` and `runner-host`. This should be cleaned up to use an appropriate library.
- https://github.com/a1ien/rusb/issues/211 may either be related to the above 2 points or something else (but it seems the runner image is the same as yesterday where the test was passing, so it must be a change in this PR and it must be specific to `runner-host` since `scheduler` is fine, so probably the first point rather than the second point)

2024-09-26 13:35 UTC, ia0-review approved these changes

2024-09-26 13:35 UTC, merged

2024-09-26 15:47 UTC, ia0 commented
Ok the issues have been understood: 
- #619 fixes the first issue 
- `cargo check` doesn't care what `libapplet.a` is as long as it exists, so we should just touch it
- the issue was that we compiled `rusb` in a device, this is fixed by #619 (initially fixed by #618 but the wrong fix)

2024-09-27 08:17 UTC, ia0 commented
Sending #620 for the remaining issue, essentially fixing the known issues introduced by this PR.